# Bellman's Equation
 
Sungchul Lee  

Sutton 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/bookdraft2017nov5.pdf)
Szepesvári 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Algorithms-for-Reinforcement-Learning.pdf)
Ng
[16](https://www.youtube.com/watch?v=RtxI449ZjSc&list=PLA89DCFA6ADACE599&index=16)
[demo](http://heli.stanford.edu/) 
Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

# Policy $\pi$


<div align="center"><img src="img/2007-164-water-policy.jpg" width="40%" height="10%"></div>

- When you are at state $s$, there are many actions you can choose.

- Policy descibe how you choose your action.

http://www.inkcinct.com.au/web-pages/cartoons/past/2007/2007-164-water-policy.jpg

# Policy in Andrew Ng's Lecture 16

<div align="center"><img src="img/Screenshot+2016-12-16+15.11.27.png" width="60%" height="10%"></div>

http://static1.squarespace.com/static/55ff6aece4b0ad2d251b3fee/56381d00e4b05b1abc31cd96/58546ed09de4bb1925de9469/1494102176399/Screenshot+2016-12-16+15.11.27.png?format=1000w

# Bad policy 

$$\begin{array}{cccccccc}
\Rightarrow&\Rightarrow&\Rightarrow&1\\
\Downarrow&\mbox{W}&\Rightarrow&-1\\
\Rightarrow&\Rightarrow&\Uparrow&\Uparrow\\
\end{array}$$

In [6]:
import numpy as np

N_STATES = 11
N_ACTIONS = 4

policy = np.empty((N_STATES, N_ACTIONS))
policy[0,:] = [0,1,0,0]
policy[1,:] = [0,1,0,0]
policy[2,:] = [0,1,0,0]
policy[3,:] = [0,1,0,0]
policy[4,:] = [0,0,0,1]
policy[5,:] = [0,1,0,0]
policy[6,:] = [0,1,0,0]
policy[7,:] = [0,1,0,0]
policy[8,:] = [0,1,0,0]
policy[9,:] = [0,0,1,0]
policy[10,:] = [0,0,1,0]
policy = policy.astype(np.float32)

print(policy)
print(type(policy))
print(policy.dtype)
print(policy.shape)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
<class 'numpy.ndarray'>
float32
(11, 4)


# Random policy

In [5]:
import numpy as np

N_STATES = 11
N_ACTIONS = 4

policy = 0.25*np.ones((N_STATES, N_ACTIONS))
policy = policy.astype(np.float32)

print(policy)
print(type(policy))
print(policy.dtype)
print(policy.shape)

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
<class 'numpy.ndarray'>
float32
(11, 4)


# Optimal policy

$$\begin{array}{cccccccc}
\Rightarrow&\Rightarrow&\Rightarrow&1\\
\Uparrow&\mbox{W}&\Uparrow&-1\\
\Uparrow&\Leftarrow&\Leftarrow&\Leftarrow\\
\end{array}$$

In [4]:
import numpy as np

N_STATES = 11
N_ACTIONS = 4

policy = np.empty((N_STATES, N_ACTIONS))
policy[0,:] = [0,1,0,0]
policy[1,:] = [0,1,0,0]
policy[2,:] = [0,1,0,0]
policy[3,:] = [0,1,0,0]
policy[4,:] = [0,0,1,0]
policy[5,:] = [0,0,1,0]
policy[6,:] = [0,0,1,0]
policy[7,:] = [0,0,1,0]
policy[8,:] = [1,0,0,0]
policy[9,:] = [1,0,0,0]
policy[10,:] = [1,0,0,0]
policy = policy.astype(np.float32)

print(policy)
print(type(policy))
print(policy.dtype)
print(policy.shape)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
<class 'numpy.ndarray'>
float32
(11, 4)


# Value function and Action-value function


<div align="center"><img src="img/Q-function.png" width="70%" height="10%"></div>

https://www.youtube.com/watch?v=Vd-gmo-qO5E&index=4&list=PLlMkM4tgfjnKsCWav-Z2F-MMFRx-2gMGG

$$
\begin{array}{lllll}
\mbox{Value function}&&\quad v_\pi(s)&=&E_\pi(G_t|S_t=s)\\
\mbox{Action-value function or Q function}&&\quad q_\pi(s,a)&=&E_\pi(G_t|S_t=s,A_t=a)
\end{array}
$$
where
$$
G_t=R_t+\gamma R_{t+1}+\gamma^2 R_{t+2}+\cdots++\gamma^{T-t} R_{T}
$$


<div align="center"><img src="img/nature14236-sf2.jpg" width="50%" height="10%"></div>

https://images.nature.com/full/nature-assets/nature/journal/v518/n7540/images/nature14236-sf2.jpg

# Bellman's expectation equation





<div align="center"><img src="img/Screen Shot 2017-11-18 at 8.43.35 PM.png" width="50%" height="30%"></div>

Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)

<div align="center"><img src="img/Screen Shot 2017-11-18 at 8.43.46 PM.png" width="50%" height="10%"></div>

Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)

# Optimal policy, value function, and action-value function



<div align="center"><img src="img/cs188_mdp_policy_methods.png" width="50%"></div>

https://github.com/mebusy/notes/blob/master/dev_notes/AI_CS188_MDP.md

<img src="img/Optimal Policy 1.png"/>

Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)

<img src="img/Optimal Policy 3.png"/>

Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)

# Bellman's optimality equation 





<div align="center"><img src="img/Screen Shot 2017-11-18 at 8.44.18 PM.png" width="50%" height="10%"></div>

Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)

<div align="center"><img src="img/Screen Shot 2017-11-18 at 8.44.24 PM.png" width="50%" height="10%"></div>

Silver 
[2](https://www.youtube.com/watch?v=lfHX2hHRMVQ&index=2&list=PL7-jPKtc4r78-wCZcQn5IqyuWhBZ8fOxT) 
[pdf](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement_Learning_by_David_Silver_2.pdf)