In [ ]:
run main.py

/Users/sungchul/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/sungchul/anaconda/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Network Built
[0.23482822 0.29228994 0.22427195 0.24860989]
[0.21265778 0.32536042 0.21486516 0.2471167 ]
[0.2017587  0.2849147  0.22848406 0.28484252]
[0.21281624 0.32885107 0.21300945 0.24532329]
[0.23781468 0.28359538 0.22943798 0.24915192]
[0.21137324 0.2829091  0.23683739 0.26888025]
[0.2289117  0.30189702 0.22002514 0.24916615]
[0.2184044  0.32431045 0.21164452 0.24564071]
[0.24947082 0.2562311  0.24553904 0.24875905]
[0.234621   0.2867773  0.23026723 0.24833448]
[0.24831137 0.25272965 0.2489572  0.25000182]
Episode: 0, Reward: 0.84
Episode: 1, Reward: 0.88
Episode: 2, Reward: 0.6599999999999999
Episode: 3, Reward: -1.36
Episode: 4, Reward: -1.02
Episode: 5, Reward: -1.22
Episode: 6, Reward: -1.1400000000000001
Episode: 7, Reward: -1.1600000000000001
Episode: 8, Reward: -2.400000000000001
Episode: 9, Reward: -1.02
Episode: 10, Reward: -1.24
Episode: 11, Reward: -1.2
Episode: 12, Reward: -1.22
Episode: 13, Reward: -1.18
Episode: 14, Reward: -1.24
Episode: 15, Reward: -1.06
Episode

Episode: 255, Reward: 0.84
Episode: 256, Reward: 0.9199999999999999
Episode: 257, Reward: 0.84
Episode: 258, Reward: 0.6599999999999999
Episode: 259, Reward: 0.9199999999999999
Episode: 260, Reward: 0.76
Episode: 261, Reward: 0.35999999999999976
Episode: 262, Reward: 0.94
Episode: 263, Reward: 0.5999999999999999
Episode: 264, Reward: -1.1
Episode: 265, Reward: 0.96
Episode: 266, Reward: -1.62
Episode: 267, Reward: 0.19999999999999962
Episode: 268, Reward: 0.1599999999999996
Episode: 269, Reward: 0.76
Episode: 270, Reward: 0.98
Episode: 271, Reward: -1.22
Episode: 272, Reward: -1.02
Episode: 273, Reward: 0.84
Episode: 274, Reward: 0.94
Episode: 275, Reward: 0.21999999999999964
Episode: 276, Reward: 0.86
Episode: 277, Reward: 0.88
Episode: 278, Reward: 0.9
Episode: 279, Reward: 0.43999999999999984
Episode: 280, Reward: -1.02
Episode: 281, Reward: 0.6799999999999999
Episode: 282, Reward: -1.22
Episode: 283, Reward: -1.06
Episode: 284, Reward: -1.04
Episode: 285, Reward: 0.6799999999999999

Episode: 532, Reward: 0.88
Episode: 533, Reward: 0.94
Episode: 534, Reward: -1.1600000000000001
Episode: 535, Reward: 0.9
Episode: 536, Reward: -1.06
Episode: 537, Reward: -1.12
Episode: 538, Reward: 0.6399999999999999
Episode: 539, Reward: -1.02
Episode: 540, Reward: 0.88
Episode: 541, Reward: -1.02
Episode: 542, Reward: 0.94
Episode: 543, Reward: 0.6599999999999999
Episode: 544, Reward: -1.08
Episode: 545, Reward: 0.74
Episode: 546, Reward: 0.82
Episode: 547, Reward: 0.98
Episode: 548, Reward: -1.02
Episode: 549, Reward: -1.04
Episode: 550, Reward: -1.12
Episode: 551, Reward: -1.02
Episode: 552, Reward: 0.98
Episode: 553, Reward: 0.98
Episode: 554, Reward: 0.6599999999999999
Episode: 555, Reward: 0.9199999999999999
Episode: 556, Reward: 0.9199999999999999
Episode: 557, Reward: 0.86
Episode: 558, Reward: 0.9199999999999999
Episode: 559, Reward: 0.94
Episode: 560, Reward: 0.6399999999999999
Episode: 561, Reward: 0.7
Episode: 562, Reward: 0.86
Episode: 563, Reward: -1.12
Episode: 564, R

Episode: 812, Reward: 0.76
Episode: 813, Reward: 0.88
Episode: 814, Reward: 0.96
Episode: 815, Reward: 0.86
Episode: 816, Reward: 0.6799999999999999
Episode: 817, Reward: 0.96
Episode: 818, Reward: 0.86
Episode: 819, Reward: 0.31999999999999973
Episode: 820, Reward: -1.02
Episode: 821, Reward: 0.76
Episode: 822, Reward: 0.78
Episode: 823, Reward: -1.02
Episode: 824, Reward: -1.02
Episode: 825, Reward: 0.72
Episode: 826, Reward: 0.9
Episode: 827, Reward: 0.96
Episode: 828, Reward: 0.76
Episode: 829, Reward: -1.04
Episode: 830, Reward: 0.9199999999999999
Episode: 831, Reward: -0.08000000000000052
Episode: 832, Reward: -1.02
Episode: 833, Reward: 0.3799999999999998
Episode: 834, Reward: -1.04
Episode: 835, Reward: 0.98
Episode: 836, Reward: 0.5999999999999999
Episode: 837, Reward: 0.94
Episode: 838, Reward: 0.8
Episode: 839, Reward: 0.9
Episode: 840, Reward: 0.9
Episode: 841, Reward: 0.9199999999999999
Episode: 842, Reward: 0.6799999999999999
Episode: 843, Reward: 0.78
Episode: 844, Rewar

Episode: 1082, Reward: 0.5799999999999998
Episode: 1083, Reward: 0.7
Episode: 1084, Reward: 0.94
Episode: 1085, Reward: 0.9199999999999999
Episode: 1086, Reward: 0.98
Episode: 1087, Reward: 0.84
Episode: 1088, Reward: -1.02
Episode: 1089, Reward: 0.72
Episode: 1090, Reward: 0.94
Episode: 1091, Reward: 0.84
Episode: 1092, Reward: 0.96
Episode: 1093, Reward: 0.94
Episode: 1094, Reward: -1.1
Episode: 1095, Reward: 0.9199999999999999
Episode: 1096, Reward: 0.8
Episode: 1097, Reward: 0.82
Episode: 1098, Reward: -1.02
Episode: 1099, Reward: 0.96
Episode: 1100, Reward: 0.8
Episode: 1101, Reward: 0.96
Episode: 1102, Reward: 0.9199999999999999
Episode: 1103, Reward: 0.82
Episode: 1104, Reward: -1.02
Episode: 1105, Reward: 0.94
Episode: 1106, Reward: 0.72
Episode: 1107, Reward: 0.9199999999999999
Episode: 1108, Reward: 0.94
Episode: 1109, Reward: 0.6199999999999999
Episode: 1110, Reward: 0.98
Episode: 1111, Reward: -1.08
Episode: 1112, Reward: 0.96
Episode: 1113, Reward: 0.96
Episode: 1114, Rewa

Episode: 1350, Reward: 0.6399999999999999
Episode: 1351, Reward: 0.72
Episode: 1352, Reward: 0.9199999999999999
Episode: 1353, Reward: -1.02
Episode: 1354, Reward: 0.84
Episode: 1355, Reward: 0.8
Episode: 1356, Reward: 0.5199999999999998
Episode: 1357, Reward: 0.49999999999999983
Episode: 1358, Reward: 0.9199999999999999
Episode: 1359, Reward: 0.96
Episode: 1360, Reward: 0.5399999999999998
Episode: 1361, Reward: 0.6799999999999999
Episode: 1362, Reward: 0.82
Episode: 1363, Reward: 0.94
Episode: 1364, Reward: 0.6599999999999999
Episode: 1365, Reward: 0.9
Episode: 1366, Reward: 0.74
Episode: 1367, Reward: 0.6799999999999999
Episode: 1368, Reward: 0.96
Episode: 1369, Reward: 0.9199999999999999
Episode: 1370, Reward: 0.82
Episode: 1371, Reward: 0.88
Episode: 1372, Reward: 0.84
Episode: 1373, Reward: 0.8
Episode: 1374, Reward: 0.8
Episode: 1375, Reward: 0.84
Episode: 1376, Reward: 0.88
Episode: 1377, Reward: 0.9
Episode: 1378, Reward: 0.88
Episode: 1379, Reward: -1.02
Episode: 1380, Reward:

Episode: 1591, Reward: 0.8
Episode: 1592, Reward: 0.6199999999999999
Episode: 1593, Reward: 0.5399999999999998
Episode: 1594, Reward: 0.88
Episode: 1595, Reward: -1.02
Episode: 1596, Reward: 0.98
Episode: 1597, Reward: 0.84
Episode: 1598, Reward: 0.86
Episode: 1599, Reward: 0.86
Episode: 1600, Reward: 0.84
Episode: 1601, Reward: 0.94
Episode: 1602, Reward: -1.04
Episode: 1603, Reward: -1.02
Episode: 1604, Reward: -1.02
Episode: 1605, Reward: 0.98
Episode: 1606, Reward: -1.1
Episode: 1607, Reward: 0.88
Episode: 1608, Reward: 0.6199999999999999
Episode: 1609, Reward: 0.49999999999999983
Episode: 1610, Reward: 0.5999999999999999
Episode: 1611, Reward: 0.5199999999999998
Episode: 1612, Reward: 0.82
Episode: 1613, Reward: -1.08
Episode: 1614, Reward: 0.82
Episode: 1615, Reward: 0.5399999999999998
Episode: 1616, Reward: 0.9
Episode: 1617, Reward: 0.96
Episode: 1618, Reward: 0.94
Episode: 1619, Reward: 0.6799999999999999
Episode: 1620, Reward: 0.3799999999999998
Episode: 1621, Reward: 0.82
Ep

Episode: 1873, Reward: 0.9
Episode: 1874, Reward: 0.7
Episode: 1875, Reward: 0.98
Episode: 1876, Reward: 0.7
Episode: 1877, Reward: 0.6199999999999999
Episode: 1878, Reward: 0.94
Episode: 1879, Reward: 0.88
Episode: 1880, Reward: 0.9199999999999999
Episode: 1881, Reward: 0.74
Episode: 1882, Reward: 0.98
Episode: 1883, Reward: -1.04
Episode: 1884, Reward: 0.98
Episode: 1885, Reward: 0.96
Episode: 1886, Reward: -1.08
Episode: 1887, Reward: 0.82
Episode: 1888, Reward: 0.9199999999999999
Episode: 1889, Reward: -1.02
Episode: 1890, Reward: 0.9
Episode: 1891, Reward: 0.96
Episode: 1892, Reward: 0.9199999999999999
Episode: 1893, Reward: 0.98
Episode: 1894, Reward: 0.86
Episode: 1895, Reward: 0.6599999999999999
Episode: 1896, Reward: 0.98
Episode: 1897, Reward: 0.88
Episode: 1898, Reward: 0.84
Episode: 1899, Reward: 0.96
Episode: 1900, Reward: -1.02
Episode: 1901, Reward: 0.9
Episode: 1902, Reward: 0.74
Episode: 1903, Reward: -1.02
Episode: 1904, Reward: 0.86
Episode: 1905, Reward: 0.919999999

Episode: 2165, Reward: 0.76
Episode: 2166, Reward: 0.94
Episode: 2167, Reward: 0.96
Episode: 2168, Reward: 0.78
Episode: 2169, Reward: 0.82
Episode: 2170, Reward: 0.96
Episode: 2171, Reward: 0.74
Episode: 2172, Reward: -1.1600000000000001
Episode: 2173, Reward: 0.94
Episode: 2174, Reward: 0.8
Episode: 2175, Reward: 0.9199999999999999
Episode: 2176, Reward: 0.5599999999999998
Episode: 2177, Reward: 0.76
Episode: 2178, Reward: -1.02
Episode: 2179, Reward: 0.96
Episode: 2180, Reward: 0.94
Episode: 2181, Reward: 0.78
Episode: 2182, Reward: 0.94
Episode: 2183, Reward: 0.94
Episode: 2184, Reward: 0.84
Episode: 2185, Reward: 0.88
Episode: 2186, Reward: 0.96
Episode: 2187, Reward: 0.9199999999999999
Episode: 2188, Reward: 0.86
Episode: 2189, Reward: 0.96
Episode: 2190, Reward: 0.84
Episode: 2191, Reward: -1.02
Episode: 2192, Reward: 0.96
Episode: 2193, Reward: -1.02
Episode: 2194, Reward: 0.76
Episode: 2195, Reward: -1.02
Episode: 2196, Reward: 0.45999999999999985
Episode: 2197, Reward: 0.9
Ep

Episode: 2447, Reward: 0.8
Episode: 2448, Reward: -1.02
Episode: 2449, Reward: 0.94
Episode: 2450, Reward: 0.9
Episode: 2451, Reward: 0.94
Episode: 2452, Reward: 0.9199999999999999
Episode: 2453, Reward: 0.94
Episode: 2454, Reward: 0.98
Episode: 2455, Reward: 0.98
Episode: 2456, Reward: 0.9199999999999999
Episode: 2457, Reward: 0.96
Episode: 2458, Reward: -1.1600000000000001
Episode: 2459, Reward: -1.04
Episode: 2460, Reward: 0.86
Episode: 2461, Reward: 0.98
Episode: 2462, Reward: 0.94
Episode: 2463, Reward: 0.96
Episode: 2464, Reward: 0.9
Episode: 2465, Reward: 0.88
Episode: 2466, Reward: 0.76
Episode: 2467, Reward: 0.84
Episode: 2468, Reward: 0.88
Episode: 2469, Reward: 0.9199999999999999
Episode: 2470, Reward: 0.96
Episode: 2471, Reward: 0.9199999999999999
Episode: 2472, Reward: 0.88
Episode: 2473, Reward: 0.82
Episode: 2474, Reward: 0.98
Episode: 2475, Reward: 0.96
Episode: 2476, Reward: 0.84
Episode: 2477, Reward: 0.98
Episode: 2478, Reward: 0.9199999999999999
Episode: 2479, Rewar

Episode: 2732, Reward: 0.6199999999999999
Episode: 2733, Reward: 0.8
Episode: 2734, Reward: 0.9199999999999999
Episode: 2735, Reward: 0.6799999999999999
Episode: 2736, Reward: 0.98
Episode: 2737, Reward: 0.82
Episode: 2738, Reward: -1.02
Episode: 2739, Reward: 0.9199999999999999
Episode: 2740, Reward: 0.5999999999999999
Episode: 2741, Reward: 0.98
Episode: 2742, Reward: 0.96
Episode: 2743, Reward: 0.5999999999999999
Episode: 2744, Reward: 0.6399999999999999
Episode: 2745, Reward: 0.98
Episode: 2746, Reward: 0.96
Episode: 2747, Reward: 0.82
Episode: 2748, Reward: 0.76
Episode: 2749, Reward: 0.96
Episode: 2750, Reward: 0.94
Episode: 2751, Reward: 0.98
Episode: 2752, Reward: 0.94
Episode: 2753, Reward: 0.78
Episode: 2754, Reward: 0.98
Episode: 2755, Reward: 0.09999999999999953
Episode: 2756, Reward: -1.02
Episode: 2757, Reward: 0.9199999999999999
Episode: 2758, Reward: 0.88
Episode: 2759, Reward: 0.6799999999999999
Episode: 2760, Reward: 0.98
Episode: 2761, Reward: 0.94
Episode: 2762, Rew

Episode: 3004, Reward: 0.5199999999999998
Episode: 3005, Reward: 0.94
Episode: 3006, Reward: 0.84
Episode: 3007, Reward: -1.02
Episode: 3008, Reward: 0.94
Episode: 3009, Reward: 0.72
Episode: 3010, Reward: 0.86
Episode: 3011, Reward: 0.96
Episode: 3012, Reward: 0.84
Episode: 3013, Reward: 0.98
Episode: 3014, Reward: 0.9199999999999999
Episode: 3015, Reward: 0.78
Episode: 3016, Reward: 0.78
Episode: 3017, Reward: 0.88
Episode: 3018, Reward: -1.02
Episode: 3019, Reward: 0.94
Episode: 3020, Reward: 0.6199999999999999
Episode: 3021, Reward: 0.6199999999999999
Episode: 3022, Reward: 0.96
Episode: 3023, Reward: 0.8
Episode: 3024, Reward: 0.9
Episode: 3025, Reward: 0.98
Episode: 3026, Reward: 0.84
Episode: 3027, Reward: 0.76
Episode: 3028, Reward: 0.84
Episode: 3029, Reward: -1.02
Episode: 3030, Reward: 0.82
Episode: 3031, Reward: 0.6799999999999999
Episode: 3032, Reward: 0.88
Episode: 3033, Reward: 0.78
Episode: 3034, Reward: 0.98
Episode: 3035, Reward: 0.72
Episode: 3036, Reward: 0.78
Episo

Episode: 3266, Reward: 0.1599999999999996
Episode: 3267, Reward: 0.5399999999999998
Episode: 3268, Reward: 0.5999999999999999
Episode: 3269, Reward: 0.94
Episode: 3270, Reward: 0.8
Episode: 3271, Reward: 0.94
Episode: 3272, Reward: 0.96
Episode: 3273, Reward: 0.9199999999999999
Episode: 3274, Reward: 0.78
Episode: 3275, Reward: 0.11999999999999955
Episode: 3276, Reward: 0.74
Episode: 3277, Reward: 0.6799999999999999
Episode: 3278, Reward: 0.74
Episode: 3279, Reward: -1.04
Episode: 3280, Reward: 0.96
Episode: 3281, Reward: 0.9
Episode: 3282, Reward: 0.3999999999999998
Episode: 3283, Reward: 0.7
Episode: 3284, Reward: 0.96
Episode: 3285, Reward: 0.98
Episode: 3286, Reward: 0.9199999999999999
Episode: 3287, Reward: 0.78
Episode: 3288, Reward: -0.48000000000000087
Episode: 3289, Reward: 0.74
Episode: 3290, Reward: -0.24000000000000066
Episode: 3291, Reward: 0.43999999999999984
Episode: 3292, Reward: 0.96
Episode: 3293, Reward: -1.4400000000000002
Episode: 3294, Reward: 0.5999999999999999
E

Episode: 3529, Reward: -1.02
Episode: 3530, Reward: 0.9
Episode: 3531, Reward: 0.78
Episode: 3532, Reward: 0.86
Episode: 3533, Reward: 0.31999999999999973
Episode: 3534, Reward: 0.49999999999999983
Episode: 3535, Reward: 0.76
Episode: 3536, Reward: 0.96
Episode: 3537, Reward: 0.96
Episode: 3538, Reward: 0.5999999999999999
Episode: 3539, Reward: 0.8
Episode: 3540, Reward: 0.8
Episode: 3541, Reward: 0.72
Episode: 3542, Reward: 0.72
Episode: 3543, Reward: 0.45999999999999985
Episode: 3544, Reward: 0.6799999999999999
Episode: 3545, Reward: 0.9
Episode: 3546, Reward: 0.84
Episode: 3547, Reward: 0.6199999999999999
Episode: 3548, Reward: 0.82
Episode: 3549, Reward: 0.45999999999999985
Episode: 3550, Reward: 0.7
Episode: 3551, Reward: 0.82
Episode: 3552, Reward: 0.82
Episode: 3553, Reward: 0.98
Episode: 3554, Reward: 0.5199999999999998
Episode: 3555, Reward: 0.6799999999999999
Episode: 3556, Reward: 0.98
Episode: 3557, Reward: 0.84
Episode: 3558, Reward: 0.82
Episode: 3559, Reward: 0.82
Episod

/Users/sungchul/Dropbox/Git_Run/reinforcement_learning/REINFORCE/agent.py:64: RuntimeWarning: invalid value encountered in less
  a = np.random.choice(self.env.action_space, p=pi)
