In [1]:
run main.py

/Users/sungchul/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/sungchul/anaconda/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Network Built
[0.25621167 0.19586653 0.21246107 0.3354608 ]
[0.20090677 0.22446968 0.2421339  0.3324896 ]
[0.19693841 0.28658834 0.23431669 0.28215662]
[0.2047928  0.23017381 0.22177449 0.34325892]
[0.2645326  0.18624042 0.18535334 0.3638737 ]
[0.24421254 0.20627446 0.19475031 0.3547627 ]
[0.21484745 0.25609854 0.20995109 0.31910285]
[0.24226864 0.22893241 0.22921492 0.29958403]
[0.19798097 0.2268057  0.2313094  0.34390393]
[0.20320514 0.25023344 0.27301043 0.27355093]
[0.23733813 0.24932805 0.24430117 0.26903257]
Episode: 0, Reward: 0.4
Episode: 1, Reward: -1.3
Episode: 2, Reward: -5.999999999999998
Episode: 3, Reward: -3.7999999999999994
Episode: 4, Reward: -1.2000000000000002
Episode: 5, Reward: -1.5
Episode: 6, Reward: -1.6
Episode: 7, Reward: -3.500000000000001
Episode: 8, Reward: -2.5
Episode: 9, Reward: -1.5
Episode: 10, Reward: -2.4000000000000004
Episode: 11, Reward: -1.8
Episode: 12, Reward: 0.8
Episode: 13, Reward: -3.000000000000001
Episode: 14, Reward: -1.9000000000000012


Episode: 257, Reward: -2.2
Episode: 258, Reward: 0.7
Episode: 259, Reward: 0.8
Episode: 260, Reward: -1.3
Episode: 261, Reward: 0.6
Episode: 262, Reward: -1.1
Episode: 263, Reward: 0.7
Episode: 264, Reward: -1.4000000000000001
Episode: 265, Reward: 0.4
Episode: 266, Reward: 0.6
Episode: 267, Reward: 0.4
Episode: 268, Reward: -1.2000000000000002
Episode: 269, Reward: 1.1102230246251565e-16
Episode: 270, Reward: 0.5
Episode: 271, Reward: 0.10000000000000009
Episode: 272, Reward: 0.7
Episode: 273, Reward: 0.9
Episode: 274, Reward: 0.30000000000000004
Episode: 275, Reward: 0.7
Episode: 276, Reward: 0.10000000000000009
Episode: 277, Reward: 0.10000000000000009
Episode: 278, Reward: 0.7
Episode: 279, Reward: 0.5
Episode: 280, Reward: -1.3
Episode: 281, Reward: 0.9
Episode: 282, Reward: 0.8
Episode: 283, Reward: -1.1
Episode: 284, Reward: -1.7000000000000002
Episode: 285, Reward: -1.1
Episode: 286, Reward: 0.20000000000000007
Episode: 287, Reward: 0.5
Episode: 288, Reward: 0.4
Episode: 289, R

Episode: 560, Reward: 0.8
Episode: 561, Reward: -1.1
Episode: 562, Reward: 0.4
Episode: 563, Reward: 0.4
Episode: 564, Reward: 0.4
Episode: 565, Reward: -1.2000000000000002
Episode: 566, Reward: 0.5
Episode: 567, Reward: 0.20000000000000007
Episode: 568, Reward: -1.3
Episode: 569, Reward: 0.20000000000000007
Episode: 570, Reward: 0.8
Episode: 571, Reward: 0.5
Episode: 572, Reward: 0.7
Episode: 573, Reward: 0.9
Episode: 574, Reward: -1.2000000000000002
Episode: 575, Reward: 0.4
Episode: 576, Reward: 0.8
Episode: 577, Reward: 0.5
Episode: 578, Reward: 0.30000000000000004
Episode: 579, Reward: 0.4
Episode: 580, Reward: 0.9
Episode: 581, Reward: 0.30000000000000004
Episode: 582, Reward: 0.10000000000000009
Episode: 583, Reward: 1.1102230246251565e-16
Episode: 584, Reward: -1.2000000000000002
Episode: 585, Reward: -1.1
Episode: 586, Reward: 0.4
Episode: 587, Reward: -1.5
Episode: 588, Reward: 0.10000000000000009
Episode: 589, Reward: 0.4
Episode: 590, Reward: 0.5
Episode: 591, Reward: -1.5


Episode: 877, Reward: -1.4000000000000001
Episode: 878, Reward: -0.5000000000000001
Episode: 879, Reward: 0.6
Episode: 880, Reward: 0.8
Episode: 881, Reward: -1.3
Episode: 882, Reward: -1.6
Episode: 883, Reward: 0.6
Episode: 884, Reward: 0.8
Episode: 885, Reward: -1.1
Episode: 886, Reward: 0.30000000000000004
Episode: 887, Reward: -1.4000000000000001
Episode: 888, Reward: -1.1
Episode: 889, Reward: 0.7
Episode: 890, Reward: 0.30000000000000004
Episode: 891, Reward: 0.8
Episode: 892, Reward: 0.8
Episode: 893, Reward: 0.5
Episode: 894, Reward: 0.7
Episode: 895, Reward: 0.5
Episode: 896, Reward: 0.5
Episode: 897, Reward: 0.8
Episode: 898, Reward: 0.7
Episode: 899, Reward: 0.4
Episode: 900, Reward: 0.6
Episode: 901, Reward: 0.7
Episode: 902, Reward: 0.4
Episode: 903, Reward: 0.5
Episode: 904, Reward: 0.7
Episode: 905, Reward: 0.8
Episode: 906, Reward: -0.29999999999999993
Episode: 907, Reward: 0.8
Episode: 908, Reward: 0.20000000000000007
Episode: 909, Reward: -1.2000000000000002
Episode: 

<Figure size 640x480 with 1 Axes>